#+TITLE: 07 July 2021 - 13 August 2021

Santa Cruz Weather Station finally ready

* Santa Cruz Weather Station

  All Particle Monitor shelter parts fabricated.

  | Part                  | Quan. | Designed? | Fabricated? |
  |-----------------------+-------+-----------+-------------|
  | Vent connector mount  |     1 | *         | *           |
  | Vent connector cover  |     1 | *         | *           |
  | Vent mount            |     2 | *         | *           |
  | Vent Standoff         |     2 | *         | *           |
  | PM box                |     1 | *         | *           |
  | PM lid                |     1 | *         | *           |
  | PM Baffle             |     1 | *         | *           |
  | PM Screen mount       |     2 | *         | *           |
  | PM Screen holder      |     2 | *         | *           |
  | PM Inlet shroud       |     1 | *         | *           |
  | PM box mount          |     1 | *         | *           |
  | PM box mount standoff |     2 | *         | *           |
  | Vent/UV mount         |     1 | *         | *           |
  | PM Cable assembly     |     1 | *         | (1)         |
  | UV Cable assembly     |     1 | *         | *           |
  | UV/PM Cable assembly  |     1 | *         | *           |

  (1) Likely will just reuse previous assembly

  Fixed crossed TX/RX in weather mast test jig.

  Tested, installed, and retested assembled weather mast.

  PM history graphs reinstated, but this was more fiddly than
  expected - weewx software would stop after 5-10 minutes. Eventually
  started working again for reasons not clear and has been stable
  since Friday.

  Added additional checks for pms5003 synchronization is it appeared to
  have been part of the problem, now no longer clear it was.

  Ensured that sczwx github repository matches what is actually running
  on hardware.

** Next step
   None!
* Marble Computation
  Collected materials (thin copper plate, copper PCB blanks) for prototyping.
** Next Steps
*** Continue Reversible Computation Study
*** Prototype Marble inverter
    Using dual rail differential logic (left/,right/1), an inverter
    merely switches sides. I think little "kickers" on the side should
    be sufficient for a purely mechanical approach.
* MIT OCW

  Preparation to start MIT Open CourseWare classes 18.01 (Single
  Variable Calculus) and 8.01 (Physics I - Classical Mechanics).

** Next Steps
   Start studying!
* Steel Metallophone
  Did some analysis on using 6 and 12 inch steel pipe for metallophone
  and chime construction (for Kevin).
* Faust wasm oscillator
  Built a simple web browser oscillator using Faust/WASM.
* Soap Molds
  Printed a shallower top. Still not quite right, but workable.
** Next steps
*** Make sure mold doesn't leak.
*** Have Annie try it out.
* Sun Ultra 10
  Trying to see what state it is in. Fires up but no video. Need DB25M to
  debug over serial port.
** Next steps
*** Serial debug
* Apple iMac G4
  Building userland may be a PITA due to lack of RAM. Build would often
  segfault.
** Next steps
Not sure.

* Davies Brothel
  Next hearing: 02 September; Department 37
* Linux Audio
** pvanal to spectrogram
   Enough of libriffr and libpvocf work to start pvoctool
   https://github.com/daniel-kelley/pvoctool. Have HDF5 output and
   text delimited output for octave. Can import PVOC data to octave
   spectrogram for display.
*** Next steps
   Loop analysis
** CSound programming.
   The FORTRAN of computer music. Getting up to speed.
*** Next Steps
**** loscil demo
**** spectrogram loop point analysis
** Faust programming
*** Next Steps
**** GAC Patch save/restore
**** LV2 autopatcher
    Exploratory tool to generate (was pd, ecasound, now carla) patch for arbitrary LV2 plugin:
    hook up audio inputs to signal source, audio outputs to speakers, control inputs to
    control surface, etc.
**** OSC control surface
    Some sort of GUI tool (knob/slider) to OSC messages. This may be
    as simple as a Faust UI program.
**** Faust/csound
    See if a faust generated unit works.
* EPICS
**  Next steps
*** u3scpi network port testing
*** initial EPICS interface
*** u3scpi analog/digital port reconfiguration.

* Brini Tracker II
Suspended for now.
** Next steps
*** Validate remaining standard GPS messages
*** Investigate GPS chipset data logging
*** Investigate LoRA radio interface

* wktcolor
** Next steps
*** Explore how to get a minimal coloring
    Need a specific planar graph four coloring.

* wktplot
** Next steps
   Understand why -r doesn't solve the wktvor/wktdel "sliver at edge" problem.
   Explore biological cell Voronoi organization

* AMDGPU
** Next step
*** Reverse engineer HSAKMT programming.

* Ninja v Make
** Next Step
*** clean simple measurements

* GMP Forth
** Need to think about adding floating point support
** Port to non-Linux OS
* ca-r
  Tier data finally deprecated so processing is removed.
** Next Step
None.
* Swocer
** Most crashing addressed
   Nullified 'handle' API free functions helped a lot.
   Still see some errors in operations.
** Added outline for 'bottle' test
   Added all functions believed to be needed for 'bottle' demo test.
   Test doesn't pass so is disabled.
** Next steps
   Swocer future.
   Check out what's needed for gears.
