#+TITLE: 08 May 2021 - 14 May 2021

Overcoming Audio Frustration

* Linux Audio
  Ecasound cannot host Faust generated LV2 plugins. purr-data appears
  to be able to host LADSPA plugins, and it's not clear the additional
  capabilities of LV2 are entirely necessary in that context.

  Faust programs perhaps are manageable as standalone Jack/Qt
  applications, PD plugins and CSound plugins. LV2, if needed would be
  handled separately. It is interesting to fall back to PD and
  CSound - both venerable audio applications. A rough observation is
  that many newer applications, such as ossia, incorporate so many
  dependencies that building becomes increasingly fragile.

** Faust programming
   As a programming exercise, started fleshing out a set of classic
   analog synthesizer modules based on the E-Mu 1976 modular
   synthesizer catalog. Interestingly, it's the control modules (like
   the sequencer) that are proving the most challenging.
** Next Steps
*** Analog Synthesizer modules
    Let's see how far I can get.
*** LV2 autopatcher
    Exploratory tool to generate (was pd, ecasound, now carla) patch for arbitrary LV2 plugin:
    hook up audio inputs to signal source, audio outputs to speakers, control inputs to
    control surface, etc.
*** OSC control surface
    Some sort of GUI tool (knob/slider) to OSC messages. This may be
    as simple as a Faust UI program.
*** Faust/csound
    See if a faust generated unit works.
* Santa Cruz Weather Station
** Next step
*** Check replacement sensor
*** Clean BME680/VELM6075 boards
*** Design more robust instrument shelter
    Use existing small mast for VEML6075; put others in larger shelter.

* EPICS
**  Next steps
*** u3scpi network port testing
*** initial EPICS interface
*** u3scpi analog/digital port reconfiguration.

* Brini Tracker II
Still working!
** Next steps
*** Validate remaining standard GPS messages
*** Investigate GPS chipset data logging
*** Investigate LoRA radio interface

* wktcolor
** Next steps
*** Explore how to get a minimal coloring
    Need a specific planar graph four coloring.

* wktplot
** Next steps
   Understand why -r doesn't solve the wktvor/wktdel "sliver at edge" problem.

* ca-r
** Seems to have survived Fedora 34 update
** Next Step
None

* AMDGPU
** Next step
*** Reverse engineer HSAKMT programming.

* Ninja v Make
** Next Step
*** clean simple measurements

* Conical Rolling Pin
  Conical Rolling pin worked great except the sharp point dug into the
  dough.  Point isn't necessary.
** Next Step
   Soften point.
* Reading
** Infinite Powers
   Steven Strogatz
   http://www.stevenstrogatz.com/books/infinite-powers
   History of Calculus
