#+TITLE: 13 November 2021 - 19 November 2021

Beautiful Fall!

* MIT OCW
** 18.01 - Single Variable Calculus
*** Sessions 66-73
** 8.01 - Physics I - Classical Mechanics
*** Sessions 35-37,DD3
    Complete!
*** Labs
    There's a version of the course (8.01x) that has labs. Gathering
    materials needed for such.
**** Lab Power Supply
     One of the lab items needed is a power supply. Why is it that with all
     the piles of electronic parts I have, I can't seem to locate an LM317?
     Playing around with a design for a mixed switcher and linear supply.
     Actually 2 switchers: 24V/2A switcher -> Programmable Buck Switcher -> Programmable Linear.
* LA County index map
  https://github.com/daniel-kelley/la-ca-6min-index
* Mill Controller #2
  Planning mill controller upgrade for 2022. Working concept is MachineKit
  on BeagleBoard Black. Probably will design own IO board for 5V I/O unless
  I can find something that's less expensive than what I can build.
* WWVB Decoder
  Prototyped Clock sync PLL. Works against clean waveforms, fails agains
  actual waveforms. Need to think about de-noising.
* Santa Cruz Weather Station
  Rain Gauge still working.
* Marble Computation
  Collected materials (thin copper plate, copper PCB blanks) for prototyping.
** Next Steps
*** Continue Reversible Computation Study
*** Prototype Marble inverter
    Using dual rail differential logic (left/,right/1), an inverter
    merely switches sides. Now thinking an over-center spring controlling
    a 'side gate' controlled by a pair of sense levers.
* ca-r
  Issue #33 seems to have fixed itself.
** Next Step
Wait for further breakage.
* us-index-map
** error analysis
   Started an error analysis on the USGS topomaps_all.csv index file. Nothing obvious pops up,
   and the error reported by Maureen would be impossible to catch anyway.
* Sun Ultra 10
  Trying to see what state it is in. Fires up but no video. Need DB25M to
  debug over serial port.
** Next steps
*** Serial debug
* Apple iMac G4
  Building userland may be a PITA due to lack of RAM. Build would often
  segfault.
** Next steps
Not sure.

* Davies Brothel
** New case C1923172, consolidated with *15* Parties.
** Next hearing 14jan2022. Still no PACER.
* Peter Kim
** Broadcom CSG Employee indicted for trade secret theft.
** United States v. Kim (5:21-cr-00438).
** Next hearing: 1/31/2022 01:30 PM
* Linux Audio
** pvanal to spectrogram
   Enough of libriffr and libpvocf work to start pvoctool
   https://github.com/daniel-kelley/pvoctool. Have HDF5 output and
   text delimited output for octave. Can import PVOC data to octave
   spectrogram for display.
*** Next steps
   Loop analysis
** CSound programming.
   The FORTRAN of computer music. Getting up to speed.
*** Next Steps
**** loscil demo
**** spectrogram loop point analysis
** Faust programming
*** Next Steps
**** GAC Patch save/restore
**** LV2 autopatcher
    Exploratory tool to generate (was pd, ecasound, now carla) patch for arbitrary LV2 plugin:
    hook up audio inputs to signal source, audio outputs to speakers, control inputs to
    control surface, etc.
**** OSC control surface
    Some sort of GUI tool (knob/slider) to OSC messages. This may be
    as simple as a Faust UI program.
**** Faust/csound
    See if a faust generated unit works.
* EPICS
**  Next steps
*** Started CGR-101 SCPI interface
**** Will help test u3scpi
**** Using flex/bison SCPI parser
     Output queue, unit tests. ~50% system commands done.
*** u3scpi network port testing
*** initial EPICS interface
*** u3scpi analog/digital port reconfiguration.

* Brini Tracker II
Maybe this can be simplified to just the GPS module in 'tracking' mode
(which gets carried around), and a separate docking module to extract
the data.
** Next steps
*** Validate remaining standard GPS messages
*** Investigate GPS chipset data logging
*** Investigate LoRA radio interface

* wktcolor
** Next steps
*** Explore how to get a minimal coloring
    Need a specific planar graph four coloring.

* wktplot
** Next steps
   Understand why -r doesn't solve the wktvor/wktdel "sliver at edge" problem.
   Explore biological cell Voronoi organization

* AMDGPU
** Next step
*** Reverse engineer HSAKMT programming.

* Ninja v Make
** Next Step
*** clean simple measurements

* GMP Forth
** Need to think about adding floating point support
** Port to non-Linux OS
* Swocer
** Most crashing addressed
   Nullified 'handle' API free functions helped a lot.
   Still see some errors in operations.
** Added outline for 'bottle' test
   Added all functions believed to be needed for 'bottle' demo test.
   Test doesn't pass so is disabled.
** Next steps
   Swocer future.
   Check out what's needed for gears.
