#+TITLE: 17 July 2021 - 23 July 2021

Broadcom Employees Behaving Badly

* Santa Cruz Weather Station

  Most Particle Monitor shelter parts fabricated.

  | Part                 | Quan. | Designed? | Fabricated? |
  |----------------------+-------+-----------+-------------|
  | Vent connector mount |     1 | *         | *           |
  | Vent connector cover |     1 | *         | *           |
  | Vent mount           |     2 | *         | *           |
  | PM box               |     1 | *         | *           |
  | PM lid               |     1 | *         | *           |
  | PM Baffle            |     1 | *         | *           |
  | PM Screen mount      |     2 | *         | *           |
  | PM Screen holder     |     2 | *         | *           |
  | PM Inlet shroud      |     1 | *         | *           |
  | PM box mount         |     1 | *         | *           |
  | Vent/UV mount        |     1 | *         |             |
  | PM Cable assembly    |     1 | *         | (1)         |
  | UV Cable assembly    |     1 | *         |             |

  (1) Likely will just reuse previous assembly

** Next step
*** Finish Vent/UV mount
*** Build cable assemblies
*** Test in Jig

* Soap Molds
  Printed a shallower top. Still not quite right, but workable.
** Next steps
*** Make sure mold doesn't leak.
*** Have Annie try it out.
* Sun Ultra 10
  Trying to see what state it is in. Fires up but no video. Need DB25M to
  debug over serial port.
** Next steps
*** Serial debug
* Apple iMac G4
  Also trying to see what state it is in. Had Fedora 10 (1) already. Trying
  FreeBSD 13, which boots, but pkg/port is not available.
** Next steps
*** Obtain userland source
* Criminality Analysis
  An arrest of an apparent Broadcom employee for running a brothel, with one
  site across the street from the Innovation Drive campus

  https://www.paloaltoonline.com/news/2021/06/18/man-who-allegedly-profited-off-sex-trafficking-more-than-100-women-faces-10-felonies

  has led to a bunch of study and analysis of the general
  sex-trafficking problem in the Santa Clara Valley and elsewhere.

  I have not found the indictment online (it seems I will have to go
  to the courthouse for that), so I am somewhat hampered in my
  analysis.
* Marble Run
  Finally built the "Marble Run" wooden rolling ball sculpture. Thinking
  about building more. Also: how to do computation with rolling marbles?
* Linux Audio
** pvanal to spectrogram
   Enough of libriffr and libpvocf work to start pvoctool
   https://github.com/daniel-kelley/pvoctool. Have HDF5 output and
   text delimited output for octave. Can import PVOC data to octave
   spectrogram for display.
*** Next steps
   Loop analysis
** CSound programming.
   The FORTRAN of computer music. Getting up to speed.
*** Next Steps
**** loscil demo
**** spectrogram loop point analysis
** Faust programming
*** Next Steps
**** GAC Patch save/restore
**** LV2 autopatcher
    Exploratory tool to generate (was pd, ecasound, now carla) patch for arbitrary LV2 plugin:
    hook up audio inputs to signal source, audio outputs to speakers, control inputs to
    control surface, etc.
**** OSC control surface
    Some sort of GUI tool (knob/slider) to OSC messages. This may be
    as simple as a Faust UI program.
**** Faust/csound
    See if a faust generated unit works.
* EPICS
**  Next steps
*** u3scpi network port testing
*** initial EPICS interface
*** u3scpi analog/digital port reconfiguration.

* Brini Tracker II
Suspended for now.
** Next steps
*** Validate remaining standard GPS messages
*** Investigate GPS chipset data logging
*** Investigate LoRA radio interface

* wktcolor
** Next steps
*** Explore how to get a minimal coloring
    Need a specific planar graph four coloring.

* wktplot
** Next steps
   Understand why -r doesn't solve the wktvor/wktdel "sliver at edge" problem.
   Explore biological cell Voronoi organization

* AMDGPU
** Next step
*** Reverse engineer HSAKMT programming.

* Ninja v Make
** Next Step
*** clean simple measurements

* GMP Forth
** Need to think about adding floating point support
** Port to non-Linux OS
* ca-r
  Tier data finally deprecated so processing is removed.
** Next Step
None.
* Swocer
** Most crashing addressed
   Nullified 'handle' API free functions helped a lot.
   Still see some errors in operations.
** Added outline for 'bottle' test
   Added all functions believed to be needed for 'bottle' demo test.
   Test doesn't pass so is disabled.
** Next steps
   Swocer future.
   Check out what's needed for gears.
