#+TITLE: 22 May 2021 - 28 May 2021

Last week of 'Audio Push Month'

* Linux Audio

** Faust programming
*** GAC hand-created application complete
    Some problems with 'amp' argument order
*** GAC code generator started
** Next Steps
*** Analog Synthesizer modules
    Finish GAC generator
*** Waveshaper
    Starting with set of Chebyshev polynomials. Playing around with Gray coding
    to iterate through polynomial set.
*** LV2 autopatcher
    Exploratory tool to generate (was pd, ecasound, now carla) patch for arbitrary LV2 plugin:
    hook up audio inputs to signal source, audio outputs to speakers, control inputs to
    control surface, etc.
*** OSC control surface
    Some sort of GUI tool (knob/slider) to OSC messages. This may be
    as simple as a Faust UI program.
*** Faust/csound
    See if a faust generated unit works.
* Santa Cruz Weather Station
** Next step
*** Check replacement sensor
*** Clean BME680/VELM6075 boards
*** Design more robust instrument shelter
    Use existing small mast for VEML6075; put others in larger shelter.

* EPICS
**  Next steps
*** u3scpi network port testing
*** initial EPICS interface
*** u3scpi analog/digital port reconfiguration.

* Brini Tracker II
Still working!
** Next steps
*** Validate remaining standard GPS messages
*** Investigate GPS chipset data logging
*** Investigate LoRA radio interface

* wktcolor
** Next steps
*** Explore how to get a minimal coloring
    Need a specific planar graph four coloring.

* wktplot
** Next steps
   Understand why -r doesn't solve the wktvor/wktdel "sliver at edge" problem.

* ca-r
** Had yet another 'ca-tier' change
** Next Step
None

* AMDGPU
** Next step
*** Reverse engineer HSAKMT programming.

* Ninja v Make
** Next Step
*** clean simple measurements

* Conical Rolling Pin
  Conical Rolling pin worked great except the sharp point dug into the
  dough.  Point isn't necessary.
** Next Step
   Soften point.
