c_col <- c("integer",'Date','integer','integer','integer','integer','integer')
print("alameda")
alameda <- read.table("build/out/alameda.data",colClasses = c_col)
alameda_uncertain_si <- estimate_R(alameda,method = "uncertain_si",config = si_config)
write_yaml(alameda_uncertain_si, "build/out/alameda_R.yml")
svg('build/out/alameda_uncertain_si.svg')
plot(alameda_uncertain_si)
dev.off()
alameda_I_Z <- zoo(alameda$I, alameda$dates)
alameda_I_m <- rollmean(alameda_I_Z, 7,fill = list(NA, NA, NA, NULL, NA ,NA, NA))
alameda$I_m = coredata(alameda_I_m)
alameda_g_I <- ggplot(data=alameda, aes(dates, I))+geom_col()+geom_line(aes(dates,I_m),color="red")+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/alameda_I.svg', alameda_g_I)
alameda_g_C <- ggplot(data=alameda, aes(dates, C))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/alameda_C.svg', alameda_g_C)
alameda_g_D <- ggplot(data=alameda, aes(dates, D))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/alameda_D.svg', alameda_g_D)
alameda_g_E <- ggplot(data=alameda, aes(dates, E))+geom_col()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/alameda_E.svg', alameda_g_E)
write_yaml(alameda, "build/out/alameda_Data.yml")
print("alpine")
alpine <- read.table("build/out/alpine.data",colClasses = c_col)
alpine_uncertain_si <- estimate_R(alpine,method = "uncertain_si",config = si_config)
write_yaml(alpine_uncertain_si, "build/out/alpine_R.yml")
svg('build/out/alpine_uncertain_si.svg')
plot(alpine_uncertain_si)
dev.off()
alpine_I_Z <- zoo(alpine$I, alpine$dates)
alpine_I_m <- rollmean(alpine_I_Z, 7,fill = list(NA, NA, NA, NULL, NA ,NA, NA))
alpine$I_m = coredata(alpine_I_m)
alpine_g_I <- ggplot(data=alpine, aes(dates, I))+geom_col()+geom_line(aes(dates,I_m),color="red")+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/alpine_I.svg', alpine_g_I)
alpine_g_C <- ggplot(data=alpine, aes(dates, C))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/alpine_C.svg', alpine_g_C)
alpine_g_D <- ggplot(data=alpine, aes(dates, D))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/alpine_D.svg', alpine_g_D)
alpine_g_E <- ggplot(data=alpine, aes(dates, E))+geom_col()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/alpine_E.svg', alpine_g_E)
write_yaml(alpine, "build/out/alpine_Data.yml")
print("amador")
amador <- read.table("build/out/amador.data",colClasses = c_col)
amador_uncertain_si <- estimate_R(amador,method = "uncertain_si",config = si_config)
write_yaml(amador_uncertain_si, "build/out/amador_R.yml")
svg('build/out/amador_uncertain_si.svg')
plot(amador_uncertain_si)
dev.off()
amador_I_Z <- zoo(amador$I, amador$dates)
amador_I_m <- rollmean(amador_I_Z, 7,fill = list(NA, NA, NA, NULL, NA ,NA, NA))
amador$I_m = coredata(amador_I_m)
amador_g_I <- ggplot(data=amador, aes(dates, I))+geom_col()+geom_line(aes(dates,I_m),color="red")+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/amador_I.svg', amador_g_I)
amador_g_C <- ggplot(data=amador, aes(dates, C))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/amador_C.svg', amador_g_C)
amador_g_D <- ggplot(data=amador, aes(dates, D))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/amador_D.svg', amador_g_D)
amador_g_E <- ggplot(data=amador, aes(dates, E))+geom_col()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/amador_E.svg', amador_g_E)
write_yaml(amador, "build/out/amador_Data.yml")
print("butte")
butte <- read.table("build/out/butte.data",colClasses = c_col)
butte_uncertain_si <- estimate_R(butte,method = "uncertain_si",config = si_config)
write_yaml(butte_uncertain_si, "build/out/butte_R.yml")
svg('build/out/butte_uncertain_si.svg')
plot(butte_uncertain_si)
dev.off()
butte_I_Z <- zoo(butte$I, butte$dates)
butte_I_m <- rollmean(butte_I_Z, 7,fill = list(NA, NA, NA, NULL, NA ,NA, NA))
butte$I_m = coredata(butte_I_m)
butte_g_I <- ggplot(data=butte, aes(dates, I))+geom_col()+geom_line(aes(dates,I_m),color="red")+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/butte_I.svg', butte_g_I)
butte_g_C <- ggplot(data=butte, aes(dates, C))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/butte_C.svg', butte_g_C)
butte_g_D <- ggplot(data=butte, aes(dates, D))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/butte_D.svg', butte_g_D)
butte_g_E <- ggplot(data=butte, aes(dates, E))+geom_col()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/butte_E.svg', butte_g_E)
write_yaml(butte, "build/out/butte_Data.yml")
print("calaveras")
calaveras <- read.table("build/out/calaveras.data",colClasses = c_col)
calaveras_uncertain_si <- estimate_R(calaveras,method = "uncertain_si",config = si_config)
write_yaml(calaveras_uncertain_si, "build/out/calaveras_R.yml")
svg('build/out/calaveras_uncertain_si.svg')
plot(calaveras_uncertain_si)
dev.off()
calaveras_I_Z <- zoo(calaveras$I, calaveras$dates)
calaveras_I_m <- rollmean(calaveras_I_Z, 7,fill = list(NA, NA, NA, NULL, NA ,NA, NA))
calaveras$I_m = coredata(calaveras_I_m)
calaveras_g_I <- ggplot(data=calaveras, aes(dates, I))+geom_col()+geom_line(aes(dates,I_m),color="red")+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/calaveras_I.svg', calaveras_g_I)
calaveras_g_C <- ggplot(data=calaveras, aes(dates, C))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/calaveras_C.svg', calaveras_g_C)
calaveras_g_D <- ggplot(data=calaveras, aes(dates, D))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/calaveras_D.svg', calaveras_g_D)
calaveras_g_E <- ggplot(data=calaveras, aes(dates, E))+geom_col()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/calaveras_E.svg', calaveras_g_E)
write_yaml(calaveras, "build/out/calaveras_Data.yml")
print("colusa")
colusa <- read.table("build/out/colusa.data",colClasses = c_col)
colusa_uncertain_si <- estimate_R(colusa,method = "uncertain_si",config = si_config)
write_yaml(colusa_uncertain_si, "build/out/colusa_R.yml")
svg('build/out/colusa_uncertain_si.svg')
plot(colusa_uncertain_si)
dev.off()
colusa_I_Z <- zoo(colusa$I, colusa$dates)
colusa_I_m <- rollmean(colusa_I_Z, 7,fill = list(NA, NA, NA, NULL, NA ,NA, NA))
colusa$I_m = coredata(colusa_I_m)
colusa_g_I <- ggplot(data=colusa, aes(dates, I))+geom_col()+geom_line(aes(dates,I_m),color="red")+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/colusa_I.svg', colusa_g_I)
colusa_g_C <- ggplot(data=colusa, aes(dates, C))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/colusa_C.svg', colusa_g_C)
colusa_g_D <- ggplot(data=colusa, aes(dates, D))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/colusa_D.svg', colusa_g_D)
colusa_g_E <- ggplot(data=colusa, aes(dates, E))+geom_col()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/colusa_E.svg', colusa_g_E)
write_yaml(colusa, "build/out/colusa_Data.yml")
print("contra_costa")
contra_costa <- read.table("build/out/contra_costa.data",colClasses = c_col)
contra_costa_uncertain_si <- estimate_R(contra_costa,method = "uncertain_si",config = si_config)
write_yaml(contra_costa_uncertain_si, "build/out/contra_costa_R.yml")
svg('build/out/contra_costa_uncertain_si.svg')
plot(contra_costa_uncertain_si)
dev.off()
contra_costa_I_Z <- zoo(contra_costa$I, contra_costa$dates)
contra_costa_I_m <- rollmean(contra_costa_I_Z, 7,fill = list(NA, NA, NA, NULL, NA ,NA, NA))
contra_costa$I_m = coredata(contra_costa_I_m)
contra_costa_g_I <- ggplot(data=contra_costa, aes(dates, I))+geom_col()+geom_line(aes(dates,I_m),color="red")+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/contra_costa_I.svg', contra_costa_g_I)
contra_costa_g_C <- ggplot(data=contra_costa, aes(dates, C))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/contra_costa_C.svg', contra_costa_g_C)
contra_costa_g_D <- ggplot(data=contra_costa, aes(dates, D))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/contra_costa_D.svg', contra_costa_g_D)
contra_costa_g_E <- ggplot(data=contra_costa, aes(dates, E))+geom_col()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/contra_costa_E.svg', contra_costa_g_E)
write_yaml(contra_costa, "build/out/contra_costa_Data.yml")
print("del_norte")
del_norte <- read.table("build/out/del_norte.data",colClasses = c_col)
del_norte_uncertain_si <- estimate_R(del_norte,method = "uncertain_si",config = si_config)
write_yaml(del_norte_uncertain_si, "build/out/del_norte_R.yml")
svg('build/out/del_norte_uncertain_si.svg')
plot(del_norte_uncertain_si)
dev.off()
del_norte_I_Z <- zoo(del_norte$I, del_norte$dates)
del_norte_I_m <- rollmean(del_norte_I_Z, 7,fill = list(NA, NA, NA, NULL, NA ,NA, NA))
del_norte$I_m = coredata(del_norte_I_m)
del_norte_g_I <- ggplot(data=del_norte, aes(dates, I))+geom_col()+geom_line(aes(dates,I_m),color="red")+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/del_norte_I.svg', del_norte_g_I)
del_norte_g_C <- ggplot(data=del_norte, aes(dates, C))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/del_norte_C.svg', del_norte_g_C)
del_norte_g_D <- ggplot(data=del_norte, aes(dates, D))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/del_norte_D.svg', del_norte_g_D)
del_norte_g_E <- ggplot(data=del_norte, aes(dates, E))+geom_col()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/del_norte_E.svg', del_norte_g_E)
write_yaml(del_norte, "build/out/del_norte_Data.yml")
print("el_dorado")
el_dorado <- read.table("build/out/el_dorado.data",colClasses = c_col)
el_dorado_uncertain_si <- estimate_R(el_dorado,method = "uncertain_si",config = si_config)
write_yaml(el_dorado_uncertain_si, "build/out/el_dorado_R.yml")
svg('build/out/el_dorado_uncertain_si.svg')
plot(el_dorado_uncertain_si)
dev.off()
el_dorado_I_Z <- zoo(el_dorado$I, el_dorado$dates)
el_dorado_I_m <- rollmean(el_dorado_I_Z, 7,fill = list(NA, NA, NA, NULL, NA ,NA, NA))
el_dorado$I_m = coredata(el_dorado_I_m)
el_dorado_g_I <- ggplot(data=el_dorado, aes(dates, I))+geom_col()+geom_line(aes(dates,I_m),color="red")+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/el_dorado_I.svg', el_dorado_g_I)
el_dorado_g_C <- ggplot(data=el_dorado, aes(dates, C))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/el_dorado_C.svg', el_dorado_g_C)
el_dorado_g_D <- ggplot(data=el_dorado, aes(dates, D))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/el_dorado_D.svg', el_dorado_g_D)
el_dorado_g_E <- ggplot(data=el_dorado, aes(dates, E))+geom_col()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/el_dorado_E.svg', el_dorado_g_E)
write_yaml(el_dorado, "build/out/el_dorado_Data.yml")
print("fresno")
fresno <- read.table("build/out/fresno.data",colClasses = c_col)
fresno_uncertain_si <- estimate_R(fresno,method = "uncertain_si",config = si_config)
write_yaml(fresno_uncertain_si, "build/out/fresno_R.yml")
svg('build/out/fresno_uncertain_si.svg')
plot(fresno_uncertain_si)
dev.off()
fresno_I_Z <- zoo(fresno$I, fresno$dates)
fresno_I_m <- rollmean(fresno_I_Z, 7,fill = list(NA, NA, NA, NULL, NA ,NA, NA))
fresno$I_m = coredata(fresno_I_m)
fresno_g_I <- ggplot(data=fresno, aes(dates, I))+geom_col()+geom_line(aes(dates,I_m),color="red")+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/fresno_I.svg', fresno_g_I)
fresno_g_C <- ggplot(data=fresno, aes(dates, C))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/fresno_C.svg', fresno_g_C)
fresno_g_D <- ggplot(data=fresno, aes(dates, D))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/fresno_D.svg', fresno_g_D)
fresno_g_E <- ggplot(data=fresno, aes(dates, E))+geom_col()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/fresno_E.svg', fresno_g_E)
write_yaml(fresno, "build/out/fresno_Data.yml")
print("glenn")
glenn <- read.table("build/out/glenn.data",colClasses = c_col)
glenn_uncertain_si <- estimate_R(glenn,method = "uncertain_si",config = si_config)
write_yaml(glenn_uncertain_si, "build/out/glenn_R.yml")
svg('build/out/glenn_uncertain_si.svg')
plot(glenn_uncertain_si)
dev.off()
glenn_I_Z <- zoo(glenn$I, glenn$dates)
glenn_I_m <- rollmean(glenn_I_Z, 7,fill = list(NA, NA, NA, NULL, NA ,NA, NA))
glenn$I_m = coredata(glenn_I_m)
glenn_g_I <- ggplot(data=glenn, aes(dates, I))+geom_col()+geom_line(aes(dates,I_m),color="red")+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/glenn_I.svg', glenn_g_I)
glenn_g_C <- ggplot(data=glenn, aes(dates, C))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/glenn_C.svg', glenn_g_C)
glenn_g_D <- ggplot(data=glenn, aes(dates, D))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/glenn_D.svg', glenn_g_D)
glenn_g_E <- ggplot(data=glenn, aes(dates, E))+geom_col()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/glenn_E.svg', glenn_g_E)
write_yaml(glenn, "build/out/glenn_Data.yml")
print("humboldt")
humboldt <- read.table("build/out/humboldt.data",colClasses = c_col)
humboldt_uncertain_si <- estimate_R(humboldt,method = "uncertain_si",config = si_config)
write_yaml(humboldt_uncertain_si, "build/out/humboldt_R.yml")
svg('build/out/humboldt_uncertain_si.svg')
plot(humboldt_uncertain_si)
dev.off()
humboldt_I_Z <- zoo(humboldt$I, humboldt$dates)
humboldt_I_m <- rollmean(humboldt_I_Z, 7,fill = list(NA, NA, NA, NULL, NA ,NA, NA))
humboldt$I_m = coredata(humboldt_I_m)
humboldt_g_I <- ggplot(data=humboldt, aes(dates, I))+geom_col()+geom_line(aes(dates,I_m),color="red")+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/humboldt_I.svg', humboldt_g_I)
humboldt_g_C <- ggplot(data=humboldt, aes(dates, C))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/humboldt_C.svg', humboldt_g_C)
humboldt_g_D <- ggplot(data=humboldt, aes(dates, D))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/humboldt_D.svg', humboldt_g_D)
humboldt_g_E <- ggplot(data=humboldt, aes(dates, E))+geom_col()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/humboldt_E.svg', humboldt_g_E)
write_yaml(humboldt, "build/out/humboldt_Data.yml")
print("imperial")
imperial <- read.table("build/out/imperial.data",colClasses = c_col)
imperial_uncertain_si <- estimate_R(imperial,method = "uncertain_si",config = si_config)
write_yaml(imperial_uncertain_si, "build/out/imperial_R.yml")
svg('build/out/imperial_uncertain_si.svg')
plot(imperial_uncertain_si)
dev.off()
imperial_I_Z <- zoo(imperial$I, imperial$dates)
imperial_I_m <- rollmean(imperial_I_Z, 7,fill = list(NA, NA, NA, NULL, NA ,NA, NA))
imperial$I_m = coredata(imperial_I_m)
imperial_g_I <- ggplot(data=imperial, aes(dates, I))+geom_col()+geom_line(aes(dates,I_m),color="red")+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/imperial_I.svg', imperial_g_I)
imperial_g_C <- ggplot(data=imperial, aes(dates, C))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/imperial_C.svg', imperial_g_C)
imperial_g_D <- ggplot(data=imperial, aes(dates, D))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/imperial_D.svg', imperial_g_D)
imperial_g_E <- ggplot(data=imperial, aes(dates, E))+geom_col()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/imperial_E.svg', imperial_g_E)
write_yaml(imperial, "build/out/imperial_Data.yml")
print("inyo")
inyo <- read.table("build/out/inyo.data",colClasses = c_col)
inyo_uncertain_si <- estimate_R(inyo,method = "uncertain_si",config = si_config)
write_yaml(inyo_uncertain_si, "build/out/inyo_R.yml")
svg('build/out/inyo_uncertain_si.svg')
plot(inyo_uncertain_si)
dev.off()
inyo_I_Z <- zoo(inyo$I, inyo$dates)
inyo_I_m <- rollmean(inyo_I_Z, 7,fill = list(NA, NA, NA, NULL, NA ,NA, NA))
inyo$I_m = coredata(inyo_I_m)
inyo_g_I <- ggplot(data=inyo, aes(dates, I))+geom_col()+geom_line(aes(dates,I_m),color="red")+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/inyo_I.svg', inyo_g_I)
inyo_g_C <- ggplot(data=inyo, aes(dates, C))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/inyo_C.svg', inyo_g_C)
inyo_g_D <- ggplot(data=inyo, aes(dates, D))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/inyo_D.svg', inyo_g_D)
inyo_g_E <- ggplot(data=inyo, aes(dates, E))+geom_col()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/inyo_E.svg', inyo_g_E)
write_yaml(inyo, "build/out/inyo_Data.yml")
print("kern")
kern <- read.table("build/out/kern.data",colClasses = c_col)
kern_uncertain_si <- estimate_R(kern,method = "uncertain_si",config = si_config)
write_yaml(kern_uncertain_si, "build/out/kern_R.yml")
svg('build/out/kern_uncertain_si.svg')
plot(kern_uncertain_si)
dev.off()
kern_I_Z <- zoo(kern$I, kern$dates)
kern_I_m <- rollmean(kern_I_Z, 7,fill = list(NA, NA, NA, NULL, NA ,NA, NA))
kern$I_m = coredata(kern_I_m)
kern_g_I <- ggplot(data=kern, aes(dates, I))+geom_col()+geom_line(aes(dates,I_m),color="red")+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/kern_I.svg', kern_g_I)
kern_g_C <- ggplot(data=kern, aes(dates, C))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/kern_C.svg', kern_g_C)
kern_g_D <- ggplot(data=kern, aes(dates, D))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/kern_D.svg', kern_g_D)
kern_g_E <- ggplot(data=kern, aes(dates, E))+geom_col()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/kern_E.svg', kern_g_E)
write_yaml(kern, "build/out/kern_Data.yml")
print("kings")
kings <- read.table("build/out/kings.data",colClasses = c_col)
kings_uncertain_si <- estimate_R(kings,method = "uncertain_si",config = si_config)
write_yaml(kings_uncertain_si, "build/out/kings_R.yml")
svg('build/out/kings_uncertain_si.svg')
plot(kings_uncertain_si)
dev.off()
kings_I_Z <- zoo(kings$I, kings$dates)
kings_I_m <- rollmean(kings_I_Z, 7,fill = list(NA, NA, NA, NULL, NA ,NA, NA))
kings$I_m = coredata(kings_I_m)
kings_g_I <- ggplot(data=kings, aes(dates, I))+geom_col()+geom_line(aes(dates,I_m),color="red")+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/kings_I.svg', kings_g_I)
kings_g_C <- ggplot(data=kings, aes(dates, C))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/kings_C.svg', kings_g_C)
kings_g_D <- ggplot(data=kings, aes(dates, D))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/kings_D.svg', kings_g_D)
kings_g_E <- ggplot(data=kings, aes(dates, E))+geom_col()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/kings_E.svg', kings_g_E)
write_yaml(kings, "build/out/kings_Data.yml")
print("lake")
lake <- read.table("build/out/lake.data",colClasses = c_col)
lake_uncertain_si <- estimate_R(lake,method = "uncertain_si",config = si_config)
write_yaml(lake_uncertain_si, "build/out/lake_R.yml")
svg('build/out/lake_uncertain_si.svg')
plot(lake_uncertain_si)
dev.off()
lake_I_Z <- zoo(lake$I, lake$dates)
lake_I_m <- rollmean(lake_I_Z, 7,fill = list(NA, NA, NA, NULL, NA ,NA, NA))
lake$I_m = coredata(lake_I_m)
lake_g_I <- ggplot(data=lake, aes(dates, I))+geom_col()+geom_line(aes(dates,I_m),color="red")+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/lake_I.svg', lake_g_I)
lake_g_C <- ggplot(data=lake, aes(dates, C))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/lake_C.svg', lake_g_C)
lake_g_D <- ggplot(data=lake, aes(dates, D))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/lake_D.svg', lake_g_D)
lake_g_E <- ggplot(data=lake, aes(dates, E))+geom_col()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/lake_E.svg', lake_g_E)
write_yaml(lake, "build/out/lake_Data.yml")
print("lassen")
lassen <- read.table("build/out/lassen.data",colClasses = c_col)
lassen_uncertain_si <- estimate_R(lassen,method = "uncertain_si",config = si_config)
write_yaml(lassen_uncertain_si, "build/out/lassen_R.yml")
svg('build/out/lassen_uncertain_si.svg')
plot(lassen_uncertain_si)
dev.off()
lassen_I_Z <- zoo(lassen$I, lassen$dates)
lassen_I_m <- rollmean(lassen_I_Z, 7,fill = list(NA, NA, NA, NULL, NA ,NA, NA))
lassen$I_m = coredata(lassen_I_m)
lassen_g_I <- ggplot(data=lassen, aes(dates, I))+geom_col()+geom_line(aes(dates,I_m),color="red")+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/lassen_I.svg', lassen_g_I)
lassen_g_C <- ggplot(data=lassen, aes(dates, C))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/lassen_C.svg', lassen_g_C)
lassen_g_D <- ggplot(data=lassen, aes(dates, D))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/lassen_D.svg', lassen_g_D)
lassen_g_E <- ggplot(data=lassen, aes(dates, E))+geom_col()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/lassen_E.svg', lassen_g_E)
write_yaml(lassen, "build/out/lassen_Data.yml")
print("los_angeles")
los_angeles <- read.table("build/out/los_angeles.data",colClasses = c_col)
los_angeles_uncertain_si <- estimate_R(los_angeles,method = "uncertain_si",config = si_config)
write_yaml(los_angeles_uncertain_si, "build/out/los_angeles_R.yml")
svg('build/out/los_angeles_uncertain_si.svg')
plot(los_angeles_uncertain_si)
dev.off()
los_angeles_I_Z <- zoo(los_angeles$I, los_angeles$dates)
los_angeles_I_m <- rollmean(los_angeles_I_Z, 7,fill = list(NA, NA, NA, NULL, NA ,NA, NA))
los_angeles$I_m = coredata(los_angeles_I_m)
los_angeles_g_I <- ggplot(data=los_angeles, aes(dates, I))+geom_col()+geom_line(aes(dates,I_m),color="red")+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/los_angeles_I.svg', los_angeles_g_I)
los_angeles_g_C <- ggplot(data=los_angeles, aes(dates, C))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/los_angeles_C.svg', los_angeles_g_C)
los_angeles_g_D <- ggplot(data=los_angeles, aes(dates, D))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/los_angeles_D.svg', los_angeles_g_D)
los_angeles_g_E <- ggplot(data=los_angeles, aes(dates, E))+geom_col()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/los_angeles_E.svg', los_angeles_g_E)
write_yaml(los_angeles, "build/out/los_angeles_Data.yml")
print("madera")
madera <- read.table("build/out/madera.data",colClasses = c_col)
madera_uncertain_si <- estimate_R(madera,method = "uncertain_si",config = si_config)
write_yaml(madera_uncertain_si, "build/out/madera_R.yml")
svg('build/out/madera_uncertain_si.svg')
plot(madera_uncertain_si)
dev.off()
madera_I_Z <- zoo(madera$I, madera$dates)
madera_I_m <- rollmean(madera_I_Z, 7,fill = list(NA, NA, NA, NULL, NA ,NA, NA))
madera$I_m = coredata(madera_I_m)
madera_g_I <- ggplot(data=madera, aes(dates, I))+geom_col()+geom_line(aes(dates,I_m),color="red")+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/madera_I.svg', madera_g_I)
madera_g_C <- ggplot(data=madera, aes(dates, C))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/madera_C.svg', madera_g_C)
madera_g_D <- ggplot(data=madera, aes(dates, D))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/madera_D.svg', madera_g_D)
madera_g_E <- ggplot(data=madera, aes(dates, E))+geom_col()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/madera_E.svg', madera_g_E)
write_yaml(madera, "build/out/madera_Data.yml")
print("marin")
marin <- read.table("build/out/marin.data",colClasses = c_col)
marin_uncertain_si <- estimate_R(marin,method = "uncertain_si",config = si_config)
write_yaml(marin_uncertain_si, "build/out/marin_R.yml")
svg('build/out/marin_uncertain_si.svg')
plot(marin_uncertain_si)
dev.off()
marin_I_Z <- zoo(marin$I, marin$dates)
marin_I_m <- rollmean(marin_I_Z, 7,fill = list(NA, NA, NA, NULL, NA ,NA, NA))
marin$I_m = coredata(marin_I_m)
marin_g_I <- ggplot(data=marin, aes(dates, I))+geom_col()+geom_line(aes(dates,I_m),color="red")+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/marin_I.svg', marin_g_I)
marin_g_C <- ggplot(data=marin, aes(dates, C))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/marin_C.svg', marin_g_C)
marin_g_D <- ggplot(data=marin, aes(dates, D))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/marin_D.svg', marin_g_D)
marin_g_E <- ggplot(data=marin, aes(dates, E))+geom_col()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/marin_E.svg', marin_g_E)
write_yaml(marin, "build/out/marin_Data.yml")
print("mariposa")
mariposa <- read.table("build/out/mariposa.data",colClasses = c_col)
mariposa_uncertain_si <- estimate_R(mariposa,method = "uncertain_si",config = si_config)
write_yaml(mariposa_uncertain_si, "build/out/mariposa_R.yml")
svg('build/out/mariposa_uncertain_si.svg')
plot(mariposa_uncertain_si)
dev.off()
mariposa_I_Z <- zoo(mariposa$I, mariposa$dates)
mariposa_I_m <- rollmean(mariposa_I_Z, 7,fill = list(NA, NA, NA, NULL, NA ,NA, NA))
mariposa$I_m = coredata(mariposa_I_m)
mariposa_g_I <- ggplot(data=mariposa, aes(dates, I))+geom_col()+geom_line(aes(dates,I_m),color="red")+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/mariposa_I.svg', mariposa_g_I)
mariposa_g_C <- ggplot(data=mariposa, aes(dates, C))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/mariposa_C.svg', mariposa_g_C)
mariposa_g_D <- ggplot(data=mariposa, aes(dates, D))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/mariposa_D.svg', mariposa_g_D)
mariposa_g_E <- ggplot(data=mariposa, aes(dates, E))+geom_col()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/mariposa_E.svg', mariposa_g_E)
write_yaml(mariposa, "build/out/mariposa_Data.yml")
print("mendocino")
mendocino <- read.table("build/out/mendocino.data",colClasses = c_col)
mendocino_uncertain_si <- estimate_R(mendocino,method = "uncertain_si",config = si_config)
write_yaml(mendocino_uncertain_si, "build/out/mendocino_R.yml")
svg('build/out/mendocino_uncertain_si.svg')
plot(mendocino_uncertain_si)
dev.off()
mendocino_I_Z <- zoo(mendocino$I, mendocino$dates)
mendocino_I_m <- rollmean(mendocino_I_Z, 7,fill = list(NA, NA, NA, NULL, NA ,NA, NA))
mendocino$I_m = coredata(mendocino_I_m)
mendocino_g_I <- ggplot(data=mendocino, aes(dates, I))+geom_col()+geom_line(aes(dates,I_m),color="red")+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/mendocino_I.svg', mendocino_g_I)
mendocino_g_C <- ggplot(data=mendocino, aes(dates, C))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/mendocino_C.svg', mendocino_g_C)
mendocino_g_D <- ggplot(data=mendocino, aes(dates, D))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/mendocino_D.svg', mendocino_g_D)
mendocino_g_E <- ggplot(data=mendocino, aes(dates, E))+geom_col()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/mendocino_E.svg', mendocino_g_E)
write_yaml(mendocino, "build/out/mendocino_Data.yml")
print("merced")
merced <- read.table("build/out/merced.data",colClasses = c_col)
merced_uncertain_si <- estimate_R(merced,method = "uncertain_si",config = si_config)
write_yaml(merced_uncertain_si, "build/out/merced_R.yml")
svg('build/out/merced_uncertain_si.svg')
plot(merced_uncertain_si)
dev.off()
merced_I_Z <- zoo(merced$I, merced$dates)
merced_I_m <- rollmean(merced_I_Z, 7,fill = list(NA, NA, NA, NULL, NA ,NA, NA))
merced$I_m = coredata(merced_I_m)
merced_g_I <- ggplot(data=merced, aes(dates, I))+geom_col()+geom_line(aes(dates,I_m),color="red")+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/merced_I.svg', merced_g_I)
merced_g_C <- ggplot(data=merced, aes(dates, C))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/merced_C.svg', merced_g_C)
merced_g_D <- ggplot(data=merced, aes(dates, D))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/merced_D.svg', merced_g_D)
merced_g_E <- ggplot(data=merced, aes(dates, E))+geom_col()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/merced_E.svg', merced_g_E)
write_yaml(merced, "build/out/merced_Data.yml")
print("modoc")
modoc <- read.table("build/out/modoc.data",colClasses = c_col)
modoc_uncertain_si <- estimate_R(modoc,method = "uncertain_si",config = si_config)
write_yaml(modoc_uncertain_si, "build/out/modoc_R.yml")
svg('build/out/modoc_uncertain_si.svg')
plot(modoc_uncertain_si)
dev.off()
modoc_I_Z <- zoo(modoc$I, modoc$dates)
modoc_I_m <- rollmean(modoc_I_Z, 7,fill = list(NA, NA, NA, NULL, NA ,NA, NA))
modoc$I_m = coredata(modoc_I_m)
modoc_g_I <- ggplot(data=modoc, aes(dates, I))+geom_col()+geom_line(aes(dates,I_m),color="red")+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/modoc_I.svg', modoc_g_I)
modoc_g_C <- ggplot(data=modoc, aes(dates, C))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/modoc_C.svg', modoc_g_C)
modoc_g_D <- ggplot(data=modoc, aes(dates, D))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/modoc_D.svg', modoc_g_D)
modoc_g_E <- ggplot(data=modoc, aes(dates, E))+geom_col()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/modoc_E.svg', modoc_g_E)
write_yaml(modoc, "build/out/modoc_Data.yml")
print("mono")
mono <- read.table("build/out/mono.data",colClasses = c_col)
mono_uncertain_si <- estimate_R(mono,method = "uncertain_si",config = si_config)
write_yaml(mono_uncertain_si, "build/out/mono_R.yml")
svg('build/out/mono_uncertain_si.svg')
plot(mono_uncertain_si)
dev.off()
mono_I_Z <- zoo(mono$I, mono$dates)
mono_I_m <- rollmean(mono_I_Z, 7,fill = list(NA, NA, NA, NULL, NA ,NA, NA))
mono$I_m = coredata(mono_I_m)
mono_g_I <- ggplot(data=mono, aes(dates, I))+geom_col()+geom_line(aes(dates,I_m),color="red")+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/mono_I.svg', mono_g_I)
mono_g_C <- ggplot(data=mono, aes(dates, C))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/mono_C.svg', mono_g_C)
mono_g_D <- ggplot(data=mono, aes(dates, D))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/mono_D.svg', mono_g_D)
mono_g_E <- ggplot(data=mono, aes(dates, E))+geom_col()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/mono_E.svg', mono_g_E)
write_yaml(mono, "build/out/mono_Data.yml")
print("monterey")
monterey <- read.table("build/out/monterey.data",colClasses = c_col)
monterey_uncertain_si <- estimate_R(monterey,method = "uncertain_si",config = si_config)
write_yaml(monterey_uncertain_si, "build/out/monterey_R.yml")
svg('build/out/monterey_uncertain_si.svg')
plot(monterey_uncertain_si)
dev.off()
monterey_I_Z <- zoo(monterey$I, monterey$dates)
monterey_I_m <- rollmean(monterey_I_Z, 7,fill = list(NA, NA, NA, NULL, NA ,NA, NA))
monterey$I_m = coredata(monterey_I_m)
monterey_g_I <- ggplot(data=monterey, aes(dates, I))+geom_col()+geom_line(aes(dates,I_m),color="red")+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/monterey_I.svg', monterey_g_I)
monterey_g_C <- ggplot(data=monterey, aes(dates, C))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/monterey_C.svg', monterey_g_C)
monterey_g_D <- ggplot(data=monterey, aes(dates, D))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/monterey_D.svg', monterey_g_D)
monterey_g_E <- ggplot(data=monterey, aes(dates, E))+geom_col()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/monterey_E.svg', monterey_g_E)
write_yaml(monterey, "build/out/monterey_Data.yml")
print("napa")
napa <- read.table("build/out/napa.data",colClasses = c_col)
napa_uncertain_si <- estimate_R(napa,method = "uncertain_si",config = si_config)
write_yaml(napa_uncertain_si, "build/out/napa_R.yml")
svg('build/out/napa_uncertain_si.svg')
plot(napa_uncertain_si)
dev.off()
napa_I_Z <- zoo(napa$I, napa$dates)
napa_I_m <- rollmean(napa_I_Z, 7,fill = list(NA, NA, NA, NULL, NA ,NA, NA))
napa$I_m = coredata(napa_I_m)
napa_g_I <- ggplot(data=napa, aes(dates, I))+geom_col()+geom_line(aes(dates,I_m),color="red")+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/napa_I.svg', napa_g_I)
napa_g_C <- ggplot(data=napa, aes(dates, C))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/napa_C.svg', napa_g_C)
napa_g_D <- ggplot(data=napa, aes(dates, D))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/napa_D.svg', napa_g_D)
napa_g_E <- ggplot(data=napa, aes(dates, E))+geom_col()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/napa_E.svg', napa_g_E)
write_yaml(napa, "build/out/napa_Data.yml")
print("nevada")
nevada <- read.table("build/out/nevada.data",colClasses = c_col)
nevada_uncertain_si <- estimate_R(nevada,method = "uncertain_si",config = si_config)
write_yaml(nevada_uncertain_si, "build/out/nevada_R.yml")
svg('build/out/nevada_uncertain_si.svg')
plot(nevada_uncertain_si)
dev.off()
nevada_I_Z <- zoo(nevada$I, nevada$dates)
nevada_I_m <- rollmean(nevada_I_Z, 7,fill = list(NA, NA, NA, NULL, NA ,NA, NA))
nevada$I_m = coredata(nevada_I_m)
nevada_g_I <- ggplot(data=nevada, aes(dates, I))+geom_col()+geom_line(aes(dates,I_m),color="red")+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/nevada_I.svg', nevada_g_I)
nevada_g_C <- ggplot(data=nevada, aes(dates, C))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/nevada_C.svg', nevada_g_C)
nevada_g_D <- ggplot(data=nevada, aes(dates, D))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/nevada_D.svg', nevada_g_D)
nevada_g_E <- ggplot(data=nevada, aes(dates, E))+geom_col()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/nevada_E.svg', nevada_g_E)
write_yaml(nevada, "build/out/nevada_Data.yml")
print("orange")
orange <- read.table("build/out/orange.data",colClasses = c_col)
orange_uncertain_si <- estimate_R(orange,method = "uncertain_si",config = si_config)
write_yaml(orange_uncertain_si, "build/out/orange_R.yml")
svg('build/out/orange_uncertain_si.svg')
plot(orange_uncertain_si)
dev.off()
orange_I_Z <- zoo(orange$I, orange$dates)
orange_I_m <- rollmean(orange_I_Z, 7,fill = list(NA, NA, NA, NULL, NA ,NA, NA))
orange$I_m = coredata(orange_I_m)
orange_g_I <- ggplot(data=orange, aes(dates, I))+geom_col()+geom_line(aes(dates,I_m),color="red")+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/orange_I.svg', orange_g_I)
orange_g_C <- ggplot(data=orange, aes(dates, C))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/orange_C.svg', orange_g_C)
orange_g_D <- ggplot(data=orange, aes(dates, D))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/orange_D.svg', orange_g_D)
orange_g_E <- ggplot(data=orange, aes(dates, E))+geom_col()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/orange_E.svg', orange_g_E)
write_yaml(orange, "build/out/orange_Data.yml")
print("placer")
placer <- read.table("build/out/placer.data",colClasses = c_col)
placer_uncertain_si <- estimate_R(placer,method = "uncertain_si",config = si_config)
write_yaml(placer_uncertain_si, "build/out/placer_R.yml")
svg('build/out/placer_uncertain_si.svg')
plot(placer_uncertain_si)
dev.off()
placer_I_Z <- zoo(placer$I, placer$dates)
placer_I_m <- rollmean(placer_I_Z, 7,fill = list(NA, NA, NA, NULL, NA ,NA, NA))
placer$I_m = coredata(placer_I_m)
placer_g_I <- ggplot(data=placer, aes(dates, I))+geom_col()+geom_line(aes(dates,I_m),color="red")+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/placer_I.svg', placer_g_I)
placer_g_C <- ggplot(data=placer, aes(dates, C))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/placer_C.svg', placer_g_C)
placer_g_D <- ggplot(data=placer, aes(dates, D))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/placer_D.svg', placer_g_D)
placer_g_E <- ggplot(data=placer, aes(dates, E))+geom_col()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/placer_E.svg', placer_g_E)
write_yaml(placer, "build/out/placer_Data.yml")
print("plumas")
plumas <- read.table("build/out/plumas.data",colClasses = c_col)
plumas_uncertain_si <- estimate_R(plumas,method = "uncertain_si",config = si_config)
write_yaml(plumas_uncertain_si, "build/out/plumas_R.yml")
svg('build/out/plumas_uncertain_si.svg')
plot(plumas_uncertain_si)
dev.off()
plumas_I_Z <- zoo(plumas$I, plumas$dates)
plumas_I_m <- rollmean(plumas_I_Z, 7,fill = list(NA, NA, NA, NULL, NA ,NA, NA))
plumas$I_m = coredata(plumas_I_m)
plumas_g_I <- ggplot(data=plumas, aes(dates, I))+geom_col()+geom_line(aes(dates,I_m),color="red")+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/plumas_I.svg', plumas_g_I)
plumas_g_C <- ggplot(data=plumas, aes(dates, C))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/plumas_C.svg', plumas_g_C)
plumas_g_D <- ggplot(data=plumas, aes(dates, D))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/plumas_D.svg', plumas_g_D)
plumas_g_E <- ggplot(data=plumas, aes(dates, E))+geom_col()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/plumas_E.svg', plumas_g_E)
write_yaml(plumas, "build/out/plumas_Data.yml")
print("riverside")
riverside <- read.table("build/out/riverside.data",colClasses = c_col)
riverside_uncertain_si <- estimate_R(riverside,method = "uncertain_si",config = si_config)
write_yaml(riverside_uncertain_si, "build/out/riverside_R.yml")
svg('build/out/riverside_uncertain_si.svg')
plot(riverside_uncertain_si)
dev.off()
riverside_I_Z <- zoo(riverside$I, riverside$dates)
riverside_I_m <- rollmean(riverside_I_Z, 7,fill = list(NA, NA, NA, NULL, NA ,NA, NA))
riverside$I_m = coredata(riverside_I_m)
riverside_g_I <- ggplot(data=riverside, aes(dates, I))+geom_col()+geom_line(aes(dates,I_m),color="red")+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/riverside_I.svg', riverside_g_I)
riverside_g_C <- ggplot(data=riverside, aes(dates, C))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/riverside_C.svg', riverside_g_C)
riverside_g_D <- ggplot(data=riverside, aes(dates, D))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/riverside_D.svg', riverside_g_D)
riverside_g_E <- ggplot(data=riverside, aes(dates, E))+geom_col()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/riverside_E.svg', riverside_g_E)
write_yaml(riverside, "build/out/riverside_Data.yml")
print("sacramento")
sacramento <- read.table("build/out/sacramento.data",colClasses = c_col)
sacramento_uncertain_si <- estimate_R(sacramento,method = "uncertain_si",config = si_config)
write_yaml(sacramento_uncertain_si, "build/out/sacramento_R.yml")
svg('build/out/sacramento_uncertain_si.svg')
plot(sacramento_uncertain_si)
dev.off()
sacramento_I_Z <- zoo(sacramento$I, sacramento$dates)
sacramento_I_m <- rollmean(sacramento_I_Z, 7,fill = list(NA, NA, NA, NULL, NA ,NA, NA))
sacramento$I_m = coredata(sacramento_I_m)
sacramento_g_I <- ggplot(data=sacramento, aes(dates, I))+geom_col()+geom_line(aes(dates,I_m),color="red")+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/sacramento_I.svg', sacramento_g_I)
sacramento_g_C <- ggplot(data=sacramento, aes(dates, C))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/sacramento_C.svg', sacramento_g_C)
sacramento_g_D <- ggplot(data=sacramento, aes(dates, D))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/sacramento_D.svg', sacramento_g_D)
sacramento_g_E <- ggplot(data=sacramento, aes(dates, E))+geom_col()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/sacramento_E.svg', sacramento_g_E)
write_yaml(sacramento, "build/out/sacramento_Data.yml")
print("san_benito")
san_benito <- read.table("build/out/san_benito.data",colClasses = c_col)
san_benito_uncertain_si <- estimate_R(san_benito,method = "uncertain_si",config = si_config)
write_yaml(san_benito_uncertain_si, "build/out/san_benito_R.yml")
svg('build/out/san_benito_uncertain_si.svg')
plot(san_benito_uncertain_si)
dev.off()
san_benito_I_Z <- zoo(san_benito$I, san_benito$dates)
san_benito_I_m <- rollmean(san_benito_I_Z, 7,fill = list(NA, NA, NA, NULL, NA ,NA, NA))
san_benito$I_m = coredata(san_benito_I_m)
san_benito_g_I <- ggplot(data=san_benito, aes(dates, I))+geom_col()+geom_line(aes(dates,I_m),color="red")+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/san_benito_I.svg', san_benito_g_I)
san_benito_g_C <- ggplot(data=san_benito, aes(dates, C))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/san_benito_C.svg', san_benito_g_C)
san_benito_g_D <- ggplot(data=san_benito, aes(dates, D))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/san_benito_D.svg', san_benito_g_D)
san_benito_g_E <- ggplot(data=san_benito, aes(dates, E))+geom_col()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/san_benito_E.svg', san_benito_g_E)
write_yaml(san_benito, "build/out/san_benito_Data.yml")
print("san_bernardino")
san_bernardino <- read.table("build/out/san_bernardino.data",colClasses = c_col)
san_bernardino_uncertain_si <- estimate_R(san_bernardino,method = "uncertain_si",config = si_config)
write_yaml(san_bernardino_uncertain_si, "build/out/san_bernardino_R.yml")
svg('build/out/san_bernardino_uncertain_si.svg')
plot(san_bernardino_uncertain_si)
dev.off()
san_bernardino_I_Z <- zoo(san_bernardino$I, san_bernardino$dates)
san_bernardino_I_m <- rollmean(san_bernardino_I_Z, 7,fill = list(NA, NA, NA, NULL, NA ,NA, NA))
san_bernardino$I_m = coredata(san_bernardino_I_m)
san_bernardino_g_I <- ggplot(data=san_bernardino, aes(dates, I))+geom_col()+geom_line(aes(dates,I_m),color="red")+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/san_bernardino_I.svg', san_bernardino_g_I)
san_bernardino_g_C <- ggplot(data=san_bernardino, aes(dates, C))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/san_bernardino_C.svg', san_bernardino_g_C)
san_bernardino_g_D <- ggplot(data=san_bernardino, aes(dates, D))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/san_bernardino_D.svg', san_bernardino_g_D)
san_bernardino_g_E <- ggplot(data=san_bernardino, aes(dates, E))+geom_col()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/san_bernardino_E.svg', san_bernardino_g_E)
write_yaml(san_bernardino, "build/out/san_bernardino_Data.yml")
print("san_diego")
san_diego <- read.table("build/out/san_diego.data",colClasses = c_col)
san_diego_uncertain_si <- estimate_R(san_diego,method = "uncertain_si",config = si_config)
write_yaml(san_diego_uncertain_si, "build/out/san_diego_R.yml")
svg('build/out/san_diego_uncertain_si.svg')
plot(san_diego_uncertain_si)
dev.off()
san_diego_I_Z <- zoo(san_diego$I, san_diego$dates)
san_diego_I_m <- rollmean(san_diego_I_Z, 7,fill = list(NA, NA, NA, NULL, NA ,NA, NA))
san_diego$I_m = coredata(san_diego_I_m)
san_diego_g_I <- ggplot(data=san_diego, aes(dates, I))+geom_col()+geom_line(aes(dates,I_m),color="red")+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/san_diego_I.svg', san_diego_g_I)
san_diego_g_C <- ggplot(data=san_diego, aes(dates, C))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/san_diego_C.svg', san_diego_g_C)
san_diego_g_D <- ggplot(data=san_diego, aes(dates, D))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/san_diego_D.svg', san_diego_g_D)
san_diego_g_E <- ggplot(data=san_diego, aes(dates, E))+geom_col()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/san_diego_E.svg', san_diego_g_E)
write_yaml(san_diego, "build/out/san_diego_Data.yml")
print("san_francisco")
san_francisco <- read.table("build/out/san_francisco.data",colClasses = c_col)
san_francisco_uncertain_si <- estimate_R(san_francisco,method = "uncertain_si",config = si_config)
write_yaml(san_francisco_uncertain_si, "build/out/san_francisco_R.yml")
svg('build/out/san_francisco_uncertain_si.svg')
plot(san_francisco_uncertain_si)
dev.off()
san_francisco_I_Z <- zoo(san_francisco$I, san_francisco$dates)
san_francisco_I_m <- rollmean(san_francisco_I_Z, 7,fill = list(NA, NA, NA, NULL, NA ,NA, NA))
san_francisco$I_m = coredata(san_francisco_I_m)
san_francisco_g_I <- ggplot(data=san_francisco, aes(dates, I))+geom_col()+geom_line(aes(dates,I_m),color="red")+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/san_francisco_I.svg', san_francisco_g_I)
san_francisco_g_C <- ggplot(data=san_francisco, aes(dates, C))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/san_francisco_C.svg', san_francisco_g_C)
san_francisco_g_D <- ggplot(data=san_francisco, aes(dates, D))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/san_francisco_D.svg', san_francisco_g_D)
san_francisco_g_E <- ggplot(data=san_francisco, aes(dates, E))+geom_col()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/san_francisco_E.svg', san_francisco_g_E)
write_yaml(san_francisco, "build/out/san_francisco_Data.yml")
print("san_joaquin")
san_joaquin <- read.table("build/out/san_joaquin.data",colClasses = c_col)
san_joaquin_uncertain_si <- estimate_R(san_joaquin,method = "uncertain_si",config = si_config)
write_yaml(san_joaquin_uncertain_si, "build/out/san_joaquin_R.yml")
svg('build/out/san_joaquin_uncertain_si.svg')
plot(san_joaquin_uncertain_si)
dev.off()
san_joaquin_I_Z <- zoo(san_joaquin$I, san_joaquin$dates)
san_joaquin_I_m <- rollmean(san_joaquin_I_Z, 7,fill = list(NA, NA, NA, NULL, NA ,NA, NA))
san_joaquin$I_m = coredata(san_joaquin_I_m)
san_joaquin_g_I <- ggplot(data=san_joaquin, aes(dates, I))+geom_col()+geom_line(aes(dates,I_m),color="red")+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/san_joaquin_I.svg', san_joaquin_g_I)
san_joaquin_g_C <- ggplot(data=san_joaquin, aes(dates, C))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/san_joaquin_C.svg', san_joaquin_g_C)
san_joaquin_g_D <- ggplot(data=san_joaquin, aes(dates, D))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/san_joaquin_D.svg', san_joaquin_g_D)
san_joaquin_g_E <- ggplot(data=san_joaquin, aes(dates, E))+geom_col()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/san_joaquin_E.svg', san_joaquin_g_E)
write_yaml(san_joaquin, "build/out/san_joaquin_Data.yml")
print("san_luis_obispo")
san_luis_obispo <- read.table("build/out/san_luis_obispo.data",colClasses = c_col)
san_luis_obispo_uncertain_si <- estimate_R(san_luis_obispo,method = "uncertain_si",config = si_config)
write_yaml(san_luis_obispo_uncertain_si, "build/out/san_luis_obispo_R.yml")
svg('build/out/san_luis_obispo_uncertain_si.svg')
plot(san_luis_obispo_uncertain_si)
dev.off()
san_luis_obispo_I_Z <- zoo(san_luis_obispo$I, san_luis_obispo$dates)
san_luis_obispo_I_m <- rollmean(san_luis_obispo_I_Z, 7,fill = list(NA, NA, NA, NULL, NA ,NA, NA))
san_luis_obispo$I_m = coredata(san_luis_obispo_I_m)
san_luis_obispo_g_I <- ggplot(data=san_luis_obispo, aes(dates, I))+geom_col()+geom_line(aes(dates,I_m),color="red")+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/san_luis_obispo_I.svg', san_luis_obispo_g_I)
san_luis_obispo_g_C <- ggplot(data=san_luis_obispo, aes(dates, C))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/san_luis_obispo_C.svg', san_luis_obispo_g_C)
san_luis_obispo_g_D <- ggplot(data=san_luis_obispo, aes(dates, D))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/san_luis_obispo_D.svg', san_luis_obispo_g_D)
san_luis_obispo_g_E <- ggplot(data=san_luis_obispo, aes(dates, E))+geom_col()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/san_luis_obispo_E.svg', san_luis_obispo_g_E)
write_yaml(san_luis_obispo, "build/out/san_luis_obispo_Data.yml")
print("san_mateo")
san_mateo <- read.table("build/out/san_mateo.data",colClasses = c_col)
san_mateo_uncertain_si <- estimate_R(san_mateo,method = "uncertain_si",config = si_config)
write_yaml(san_mateo_uncertain_si, "build/out/san_mateo_R.yml")
svg('build/out/san_mateo_uncertain_si.svg')
plot(san_mateo_uncertain_si)
dev.off()
san_mateo_I_Z <- zoo(san_mateo$I, san_mateo$dates)
san_mateo_I_m <- rollmean(san_mateo_I_Z, 7,fill = list(NA, NA, NA, NULL, NA ,NA, NA))
san_mateo$I_m = coredata(san_mateo_I_m)
san_mateo_g_I <- ggplot(data=san_mateo, aes(dates, I))+geom_col()+geom_line(aes(dates,I_m),color="red")+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/san_mateo_I.svg', san_mateo_g_I)
san_mateo_g_C <- ggplot(data=san_mateo, aes(dates, C))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/san_mateo_C.svg', san_mateo_g_C)
san_mateo_g_D <- ggplot(data=san_mateo, aes(dates, D))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/san_mateo_D.svg', san_mateo_g_D)
san_mateo_g_E <- ggplot(data=san_mateo, aes(dates, E))+geom_col()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/san_mateo_E.svg', san_mateo_g_E)
write_yaml(san_mateo, "build/out/san_mateo_Data.yml")
print("santa_barbara")
santa_barbara <- read.table("build/out/santa_barbara.data",colClasses = c_col)
santa_barbara_uncertain_si <- estimate_R(santa_barbara,method = "uncertain_si",config = si_config)
write_yaml(santa_barbara_uncertain_si, "build/out/santa_barbara_R.yml")
svg('build/out/santa_barbara_uncertain_si.svg')
plot(santa_barbara_uncertain_si)
dev.off()
santa_barbara_I_Z <- zoo(santa_barbara$I, santa_barbara$dates)
santa_barbara_I_m <- rollmean(santa_barbara_I_Z, 7,fill = list(NA, NA, NA, NULL, NA ,NA, NA))
santa_barbara$I_m = coredata(santa_barbara_I_m)
santa_barbara_g_I <- ggplot(data=santa_barbara, aes(dates, I))+geom_col()+geom_line(aes(dates,I_m),color="red")+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/santa_barbara_I.svg', santa_barbara_g_I)
santa_barbara_g_C <- ggplot(data=santa_barbara, aes(dates, C))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/santa_barbara_C.svg', santa_barbara_g_C)
santa_barbara_g_D <- ggplot(data=santa_barbara, aes(dates, D))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/santa_barbara_D.svg', santa_barbara_g_D)
santa_barbara_g_E <- ggplot(data=santa_barbara, aes(dates, E))+geom_col()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/santa_barbara_E.svg', santa_barbara_g_E)
write_yaml(santa_barbara, "build/out/santa_barbara_Data.yml")
print("santa_clara")
santa_clara <- read.table("build/out/santa_clara.data",colClasses = c_col)
santa_clara_uncertain_si <- estimate_R(santa_clara,method = "uncertain_si",config = si_config)
write_yaml(santa_clara_uncertain_si, "build/out/santa_clara_R.yml")
svg('build/out/santa_clara_uncertain_si.svg')
plot(santa_clara_uncertain_si)
dev.off()
santa_clara_I_Z <- zoo(santa_clara$I, santa_clara$dates)
santa_clara_I_m <- rollmean(santa_clara_I_Z, 7,fill = list(NA, NA, NA, NULL, NA ,NA, NA))
santa_clara$I_m = coredata(santa_clara_I_m)
santa_clara_g_I <- ggplot(data=santa_clara, aes(dates, I))+geom_col()+geom_line(aes(dates,I_m),color="red")+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/santa_clara_I.svg', santa_clara_g_I)
santa_clara_g_C <- ggplot(data=santa_clara, aes(dates, C))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/santa_clara_C.svg', santa_clara_g_C)
santa_clara_g_D <- ggplot(data=santa_clara, aes(dates, D))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/santa_clara_D.svg', santa_clara_g_D)
santa_clara_g_E <- ggplot(data=santa_clara, aes(dates, E))+geom_col()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/santa_clara_E.svg', santa_clara_g_E)
write_yaml(santa_clara, "build/out/santa_clara_Data.yml")
print("santa_cruz")
santa_cruz <- read.table("build/out/santa_cruz.data",colClasses = c_col)
santa_cruz_uncertain_si <- estimate_R(santa_cruz,method = "uncertain_si",config = si_config)
write_yaml(santa_cruz_uncertain_si, "build/out/santa_cruz_R.yml")
svg('build/out/santa_cruz_uncertain_si.svg')
plot(santa_cruz_uncertain_si)
dev.off()
santa_cruz_I_Z <- zoo(santa_cruz$I, santa_cruz$dates)
santa_cruz_I_m <- rollmean(santa_cruz_I_Z, 7,fill = list(NA, NA, NA, NULL, NA ,NA, NA))
santa_cruz$I_m = coredata(santa_cruz_I_m)
santa_cruz_g_I <- ggplot(data=santa_cruz, aes(dates, I))+geom_col()+geom_line(aes(dates,I_m),color="red")+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/santa_cruz_I.svg', santa_cruz_g_I)
santa_cruz_g_C <- ggplot(data=santa_cruz, aes(dates, C))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/santa_cruz_C.svg', santa_cruz_g_C)
santa_cruz_g_D <- ggplot(data=santa_cruz, aes(dates, D))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/santa_cruz_D.svg', santa_cruz_g_D)
santa_cruz_g_E <- ggplot(data=santa_cruz, aes(dates, E))+geom_col()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/santa_cruz_E.svg', santa_cruz_g_E)
write_yaml(santa_cruz, "build/out/santa_cruz_Data.yml")
print("shasta")
shasta <- read.table("build/out/shasta.data",colClasses = c_col)
shasta_uncertain_si <- estimate_R(shasta,method = "uncertain_si",config = si_config)
write_yaml(shasta_uncertain_si, "build/out/shasta_R.yml")
svg('build/out/shasta_uncertain_si.svg')
plot(shasta_uncertain_si)
dev.off()
shasta_I_Z <- zoo(shasta$I, shasta$dates)
shasta_I_m <- rollmean(shasta_I_Z, 7,fill = list(NA, NA, NA, NULL, NA ,NA, NA))
shasta$I_m = coredata(shasta_I_m)
shasta_g_I <- ggplot(data=shasta, aes(dates, I))+geom_col()+geom_line(aes(dates,I_m),color="red")+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/shasta_I.svg', shasta_g_I)
shasta_g_C <- ggplot(data=shasta, aes(dates, C))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/shasta_C.svg', shasta_g_C)
shasta_g_D <- ggplot(data=shasta, aes(dates, D))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/shasta_D.svg', shasta_g_D)
shasta_g_E <- ggplot(data=shasta, aes(dates, E))+geom_col()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/shasta_E.svg', shasta_g_E)
write_yaml(shasta, "build/out/shasta_Data.yml")
print("sierra")
sierra <- read.table("build/out/sierra.data",colClasses = c_col)
sierra_uncertain_si <- estimate_R(sierra,method = "uncertain_si",config = si_config)
write_yaml(sierra_uncertain_si, "build/out/sierra_R.yml")
svg('build/out/sierra_uncertain_si.svg')
plot(sierra_uncertain_si)
dev.off()
sierra_I_Z <- zoo(sierra$I, sierra$dates)
sierra_I_m <- rollmean(sierra_I_Z, 7,fill = list(NA, NA, NA, NULL, NA ,NA, NA))
sierra$I_m = coredata(sierra_I_m)
sierra_g_I <- ggplot(data=sierra, aes(dates, I))+geom_col()+geom_line(aes(dates,I_m),color="red")+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/sierra_I.svg', sierra_g_I)
sierra_g_C <- ggplot(data=sierra, aes(dates, C))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/sierra_C.svg', sierra_g_C)
sierra_g_D <- ggplot(data=sierra, aes(dates, D))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/sierra_D.svg', sierra_g_D)
sierra_g_E <- ggplot(data=sierra, aes(dates, E))+geom_col()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/sierra_E.svg', sierra_g_E)
write_yaml(sierra, "build/out/sierra_Data.yml")
print("siskiyou")
siskiyou <- read.table("build/out/siskiyou.data",colClasses = c_col)
siskiyou_uncertain_si <- estimate_R(siskiyou,method = "uncertain_si",config = si_config)
write_yaml(siskiyou_uncertain_si, "build/out/siskiyou_R.yml")
svg('build/out/siskiyou_uncertain_si.svg')
plot(siskiyou_uncertain_si)
dev.off()
siskiyou_I_Z <- zoo(siskiyou$I, siskiyou$dates)
siskiyou_I_m <- rollmean(siskiyou_I_Z, 7,fill = list(NA, NA, NA, NULL, NA ,NA, NA))
siskiyou$I_m = coredata(siskiyou_I_m)
siskiyou_g_I <- ggplot(data=siskiyou, aes(dates, I))+geom_col()+geom_line(aes(dates,I_m),color="red")+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/siskiyou_I.svg', siskiyou_g_I)
siskiyou_g_C <- ggplot(data=siskiyou, aes(dates, C))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/siskiyou_C.svg', siskiyou_g_C)
siskiyou_g_D <- ggplot(data=siskiyou, aes(dates, D))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/siskiyou_D.svg', siskiyou_g_D)
siskiyou_g_E <- ggplot(data=siskiyou, aes(dates, E))+geom_col()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/siskiyou_E.svg', siskiyou_g_E)
write_yaml(siskiyou, "build/out/siskiyou_Data.yml")
print("solano")
solano <- read.table("build/out/solano.data",colClasses = c_col)
solano_uncertain_si <- estimate_R(solano,method = "uncertain_si",config = si_config)
write_yaml(solano_uncertain_si, "build/out/solano_R.yml")
svg('build/out/solano_uncertain_si.svg')
plot(solano_uncertain_si)
dev.off()
solano_I_Z <- zoo(solano$I, solano$dates)
solano_I_m <- rollmean(solano_I_Z, 7,fill = list(NA, NA, NA, NULL, NA ,NA, NA))
solano$I_m = coredata(solano_I_m)
solano_g_I <- ggplot(data=solano, aes(dates, I))+geom_col()+geom_line(aes(dates,I_m),color="red")+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/solano_I.svg', solano_g_I)
solano_g_C <- ggplot(data=solano, aes(dates, C))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/solano_C.svg', solano_g_C)
solano_g_D <- ggplot(data=solano, aes(dates, D))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/solano_D.svg', solano_g_D)
solano_g_E <- ggplot(data=solano, aes(dates, E))+geom_col()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/solano_E.svg', solano_g_E)
write_yaml(solano, "build/out/solano_Data.yml")
print("sonoma")
sonoma <- read.table("build/out/sonoma.data",colClasses = c_col)
sonoma_uncertain_si <- estimate_R(sonoma,method = "uncertain_si",config = si_config)
write_yaml(sonoma_uncertain_si, "build/out/sonoma_R.yml")
svg('build/out/sonoma_uncertain_si.svg')
plot(sonoma_uncertain_si)
dev.off()
sonoma_I_Z <- zoo(sonoma$I, sonoma$dates)
sonoma_I_m <- rollmean(sonoma_I_Z, 7,fill = list(NA, NA, NA, NULL, NA ,NA, NA))
sonoma$I_m = coredata(sonoma_I_m)
sonoma_g_I <- ggplot(data=sonoma, aes(dates, I))+geom_col()+geom_line(aes(dates,I_m),color="red")+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/sonoma_I.svg', sonoma_g_I)
sonoma_g_C <- ggplot(data=sonoma, aes(dates, C))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/sonoma_C.svg', sonoma_g_C)
sonoma_g_D <- ggplot(data=sonoma, aes(dates, D))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/sonoma_D.svg', sonoma_g_D)
sonoma_g_E <- ggplot(data=sonoma, aes(dates, E))+geom_col()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/sonoma_E.svg', sonoma_g_E)
write_yaml(sonoma, "build/out/sonoma_Data.yml")
print("stanislaus")
stanislaus <- read.table("build/out/stanislaus.data",colClasses = c_col)
stanislaus_uncertain_si <- estimate_R(stanislaus,method = "uncertain_si",config = si_config)
write_yaml(stanislaus_uncertain_si, "build/out/stanislaus_R.yml")
svg('build/out/stanislaus_uncertain_si.svg')
plot(stanislaus_uncertain_si)
dev.off()
stanislaus_I_Z <- zoo(stanislaus$I, stanislaus$dates)
stanislaus_I_m <- rollmean(stanislaus_I_Z, 7,fill = list(NA, NA, NA, NULL, NA ,NA, NA))
stanislaus$I_m = coredata(stanislaus_I_m)
stanislaus_g_I <- ggplot(data=stanislaus, aes(dates, I))+geom_col()+geom_line(aes(dates,I_m),color="red")+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/stanislaus_I.svg', stanislaus_g_I)
stanislaus_g_C <- ggplot(data=stanislaus, aes(dates, C))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/stanislaus_C.svg', stanislaus_g_C)
stanislaus_g_D <- ggplot(data=stanislaus, aes(dates, D))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/stanislaus_D.svg', stanislaus_g_D)
stanislaus_g_E <- ggplot(data=stanislaus, aes(dates, E))+geom_col()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/stanislaus_E.svg', stanislaus_g_E)
write_yaml(stanislaus, "build/out/stanislaus_Data.yml")
print("sutter")
sutter <- read.table("build/out/sutter.data",colClasses = c_col)
sutter_uncertain_si <- estimate_R(sutter,method = "uncertain_si",config = si_config)
write_yaml(sutter_uncertain_si, "build/out/sutter_R.yml")
svg('build/out/sutter_uncertain_si.svg')
plot(sutter_uncertain_si)
dev.off()
sutter_I_Z <- zoo(sutter$I, sutter$dates)
sutter_I_m <- rollmean(sutter_I_Z, 7,fill = list(NA, NA, NA, NULL, NA ,NA, NA))
sutter$I_m = coredata(sutter_I_m)
sutter_g_I <- ggplot(data=sutter, aes(dates, I))+geom_col()+geom_line(aes(dates,I_m),color="red")+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/sutter_I.svg', sutter_g_I)
sutter_g_C <- ggplot(data=sutter, aes(dates, C))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/sutter_C.svg', sutter_g_C)
sutter_g_D <- ggplot(data=sutter, aes(dates, D))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/sutter_D.svg', sutter_g_D)
sutter_g_E <- ggplot(data=sutter, aes(dates, E))+geom_col()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/sutter_E.svg', sutter_g_E)
write_yaml(sutter, "build/out/sutter_Data.yml")
print("tehama")
tehama <- read.table("build/out/tehama.data",colClasses = c_col)
tehama_uncertain_si <- estimate_R(tehama,method = "uncertain_si",config = si_config)
write_yaml(tehama_uncertain_si, "build/out/tehama_R.yml")
svg('build/out/tehama_uncertain_si.svg')
plot(tehama_uncertain_si)
dev.off()
tehama_I_Z <- zoo(tehama$I, tehama$dates)
tehama_I_m <- rollmean(tehama_I_Z, 7,fill = list(NA, NA, NA, NULL, NA ,NA, NA))
tehama$I_m = coredata(tehama_I_m)
tehama_g_I <- ggplot(data=tehama, aes(dates, I))+geom_col()+geom_line(aes(dates,I_m),color="red")+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/tehama_I.svg', tehama_g_I)
tehama_g_C <- ggplot(data=tehama, aes(dates, C))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/tehama_C.svg', tehama_g_C)
tehama_g_D <- ggplot(data=tehama, aes(dates, D))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/tehama_D.svg', tehama_g_D)
tehama_g_E <- ggplot(data=tehama, aes(dates, E))+geom_col()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/tehama_E.svg', tehama_g_E)
write_yaml(tehama, "build/out/tehama_Data.yml")
print("trinity")
trinity <- read.table("build/out/trinity.data",colClasses = c_col)
trinity_uncertain_si <- estimate_R(trinity,method = "uncertain_si",config = si_config)
write_yaml(trinity_uncertain_si, "build/out/trinity_R.yml")
svg('build/out/trinity_uncertain_si.svg')
plot(trinity_uncertain_si)
dev.off()
trinity_I_Z <- zoo(trinity$I, trinity$dates)
trinity_I_m <- rollmean(trinity_I_Z, 7,fill = list(NA, NA, NA, NULL, NA ,NA, NA))
trinity$I_m = coredata(trinity_I_m)
trinity_g_I <- ggplot(data=trinity, aes(dates, I))+geom_col()+geom_line(aes(dates,I_m),color="red")+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/trinity_I.svg', trinity_g_I)
trinity_g_C <- ggplot(data=trinity, aes(dates, C))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/trinity_C.svg', trinity_g_C)
trinity_g_D <- ggplot(data=trinity, aes(dates, D))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/trinity_D.svg', trinity_g_D)
trinity_g_E <- ggplot(data=trinity, aes(dates, E))+geom_col()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/trinity_E.svg', trinity_g_E)
write_yaml(trinity, "build/out/trinity_Data.yml")
print("tulare")
tulare <- read.table("build/out/tulare.data",colClasses = c_col)
tulare_uncertain_si <- estimate_R(tulare,method = "uncertain_si",config = si_config)
write_yaml(tulare_uncertain_si, "build/out/tulare_R.yml")
svg('build/out/tulare_uncertain_si.svg')
plot(tulare_uncertain_si)
dev.off()
tulare_I_Z <- zoo(tulare$I, tulare$dates)
tulare_I_m <- rollmean(tulare_I_Z, 7,fill = list(NA, NA, NA, NULL, NA ,NA, NA))
tulare$I_m = coredata(tulare_I_m)
tulare_g_I <- ggplot(data=tulare, aes(dates, I))+geom_col()+geom_line(aes(dates,I_m),color="red")+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/tulare_I.svg', tulare_g_I)
tulare_g_C <- ggplot(data=tulare, aes(dates, C))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/tulare_C.svg', tulare_g_C)
tulare_g_D <- ggplot(data=tulare, aes(dates, D))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/tulare_D.svg', tulare_g_D)
tulare_g_E <- ggplot(data=tulare, aes(dates, E))+geom_col()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/tulare_E.svg', tulare_g_E)
write_yaml(tulare, "build/out/tulare_Data.yml")
print("tuolumne")
tuolumne <- read.table("build/out/tuolumne.data",colClasses = c_col)
tuolumne_uncertain_si <- estimate_R(tuolumne,method = "uncertain_si",config = si_config)
write_yaml(tuolumne_uncertain_si, "build/out/tuolumne_R.yml")
svg('build/out/tuolumne_uncertain_si.svg')
plot(tuolumne_uncertain_si)
dev.off()
tuolumne_I_Z <- zoo(tuolumne$I, tuolumne$dates)
tuolumne_I_m <- rollmean(tuolumne_I_Z, 7,fill = list(NA, NA, NA, NULL, NA ,NA, NA))
tuolumne$I_m = coredata(tuolumne_I_m)
tuolumne_g_I <- ggplot(data=tuolumne, aes(dates, I))+geom_col()+geom_line(aes(dates,I_m),color="red")+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/tuolumne_I.svg', tuolumne_g_I)
tuolumne_g_C <- ggplot(data=tuolumne, aes(dates, C))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/tuolumne_C.svg', tuolumne_g_C)
tuolumne_g_D <- ggplot(data=tuolumne, aes(dates, D))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/tuolumne_D.svg', tuolumne_g_D)
tuolumne_g_E <- ggplot(data=tuolumne, aes(dates, E))+geom_col()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/tuolumne_E.svg', tuolumne_g_E)
write_yaml(tuolumne, "build/out/tuolumne_Data.yml")
print("ventura")
ventura <- read.table("build/out/ventura.data",colClasses = c_col)
ventura_uncertain_si <- estimate_R(ventura,method = "uncertain_si",config = si_config)
write_yaml(ventura_uncertain_si, "build/out/ventura_R.yml")
svg('build/out/ventura_uncertain_si.svg')
plot(ventura_uncertain_si)
dev.off()
ventura_I_Z <- zoo(ventura$I, ventura$dates)
ventura_I_m <- rollmean(ventura_I_Z, 7,fill = list(NA, NA, NA, NULL, NA ,NA, NA))
ventura$I_m = coredata(ventura_I_m)
ventura_g_I <- ggplot(data=ventura, aes(dates, I))+geom_col()+geom_line(aes(dates,I_m),color="red")+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/ventura_I.svg', ventura_g_I)
ventura_g_C <- ggplot(data=ventura, aes(dates, C))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/ventura_C.svg', ventura_g_C)
ventura_g_D <- ggplot(data=ventura, aes(dates, D))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/ventura_D.svg', ventura_g_D)
ventura_g_E <- ggplot(data=ventura, aes(dates, E))+geom_col()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/ventura_E.svg', ventura_g_E)
write_yaml(ventura, "build/out/ventura_Data.yml")
print("yolo")
yolo <- read.table("build/out/yolo.data",colClasses = c_col)
yolo_uncertain_si <- estimate_R(yolo,method = "uncertain_si",config = si_config)
write_yaml(yolo_uncertain_si, "build/out/yolo_R.yml")
svg('build/out/yolo_uncertain_si.svg')
plot(yolo_uncertain_si)
dev.off()
yolo_I_Z <- zoo(yolo$I, yolo$dates)
yolo_I_m <- rollmean(yolo_I_Z, 7,fill = list(NA, NA, NA, NULL, NA ,NA, NA))
yolo$I_m = coredata(yolo_I_m)
yolo_g_I <- ggplot(data=yolo, aes(dates, I))+geom_col()+geom_line(aes(dates,I_m),color="red")+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/yolo_I.svg', yolo_g_I)
yolo_g_C <- ggplot(data=yolo, aes(dates, C))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/yolo_C.svg', yolo_g_C)
yolo_g_D <- ggplot(data=yolo, aes(dates, D))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/yolo_D.svg', yolo_g_D)
yolo_g_E <- ggplot(data=yolo, aes(dates, E))+geom_col()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/yolo_E.svg', yolo_g_E)
write_yaml(yolo, "build/out/yolo_Data.yml")
print("yuba")
yuba <- read.table("build/out/yuba.data",colClasses = c_col)
yuba_uncertain_si <- estimate_R(yuba,method = "uncertain_si",config = si_config)
write_yaml(yuba_uncertain_si, "build/out/yuba_R.yml")
svg('build/out/yuba_uncertain_si.svg')
plot(yuba_uncertain_si)
dev.off()
yuba_I_Z <- zoo(yuba$I, yuba$dates)
yuba_I_m <- rollmean(yuba_I_Z, 7,fill = list(NA, NA, NA, NULL, NA ,NA, NA))
yuba$I_m = coredata(yuba_I_m)
yuba_g_I <- ggplot(data=yuba, aes(dates, I))+geom_col()+geom_line(aes(dates,I_m),color="red")+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/yuba_I.svg', yuba_g_I)
yuba_g_C <- ggplot(data=yuba, aes(dates, C))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/yuba_C.svg', yuba_g_C)
yuba_g_D <- ggplot(data=yuba, aes(dates, D))+geom_line()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/yuba_D.svg', yuba_g_D)
yuba_g_E <- ggplot(data=yuba, aes(dates, E))+geom_col()+scale_x_date(date_minor_breaks = "1 week")
ggsave('build/out/yuba_E.svg', yuba_g_E)
write_yaml(yuba, "build/out/yuba_Data.yml")
