#+TITLE: 08 November 2020 - 14 November 2020

It Ain't Over 'Till It's Over - Election Edition

* Live Oak Weather Station

Installed. An ME I'm not so I need to devise a better mast mount. It did go
up before a rain. See http://gmp.san-jose.ca.us/sczwx/

Software work continues.

* Swocer

Finished 3D volume API. Seems to work for basic shapes, but not for
shapes that have been cut or fused.

Used Swocer to create generators for standoffs and measuring
spoons. Made a 25mL spoon for dishwasher detergent.

Looks like Mondays are turning into "3D print Monday" so I can do
prints when I get to San Jose.

* Watercolor

Updating palette colors. Currently:

| supplier     | catalog | name                 | pigment |
|--------------+---------+----------------------+---------|
| Daler-Rowney | 414     | Quinacridone Magenta | PR122   |
| Daniel Smith |         | Ultramarine Blue     | PB29    |
| "            |         | Phthalo Green        | PG7     |
| "            |         | Pyrrol Orange        | PO73    |
| "            |         | Quinacridone red     | PV19    |
| "            |         | Phthalo Blue         | PB15:3  |
| "            |         | Hansa Yellow Medium  | PY97    |
| HWC          | W301    | Peacock Blue         | PB17    |


* Election Law Reading

https://electionlawblog.org/
