#+TITLE: 04 November 2023 - 10 November 2023

* MIT OCW
** 18.03sc (differential equations).
*** Unit IV - Matrix Methods: Eigenvalues and Normal Modes
* wood chips
Continuing.
* SCZ Front Step
** Need to take door sill to SJ to clean up
Need to rotate tablesaw to accomodate.
* Abby
** Arch installed
** Slurm install was a PITA
Alder Lake asymmetric P/E cores not well handled by slurm. Probably not
worth it to continue this direction.
* Tuffy
** Arch installed.
* Piper
** Arch installed.
Piper UEFI Bios only allows signed bootloader; so arch and debian 12
installs weren't bootble. Alma Linux would not even install (so centos
stream wasn't even tried). CentOS 7 *was* bootable, so a minimal
installation was kept and uses grub to chain load limine to boot
arch. This may have been luck.  My understanding is that UEFI signed
grub at some point disallowed chain loading unsigned EFI executables
(make sense, really). Definitely a Rube Goldberg arrangement. 50G
bootloader.
* Next arch installs
** M22 (AMD kavari box)
** Various i686
Let's see how the 32 bit version works!
* amdgpu gcn assembly framework started
It's disappointing how poor the compute support is for AMD integrated
GPUs. OpenCL and OpenMP offload both crash X driver on Kiki with
amdgpu driver complaints. Simple GCN assembly example does work, so
this effort somewhat restarts the old kaveri 'kmtrun' concept. Working
example HSA API loader in C++ is being reverse-engineered to nice,
clean, generalized C code.
* quilt block rearrangement
Another 'falling charms' quilt top needs arrangement. The existing
'quilt-block' arranger failed to find a solution, so perhaps it's time
for a high performance simulated annealing approach instead of the
ruby shuffle.
* EPLDH
** MPFI interval arithmetic better alternative
* wktpqb
** Verifying edge construction (con't.)
** 'gcd' algorithm doesn't work
* Compilers
** Started hand written WSN parser
* Mill Controller #2
** Mounted on mill - ready or testing
** Need to investigate new HW/SW for eventual replacements
*** Old crap ain't gonna last forever
*** Buildroot/Linux 5.15 PREEMPT + latency tools
First pass done - boots on real hardware
** Alternative architecture
*** Split off stepper motor controller to separate board
Increase latency tolerance on controller
*** Use emc2 MODBUS/TCP protocol for stepper and other IO
* Alum Rock Data Center
** Use Arch linux
Thanks to niece Danielle for consultation.
** Need a VPS with static IP
*** OpenVPN to tie it all together
*** Gandi VPS datacenter in France so connection crosses international border
What are the data security and privacy tradeoffs?
*** Prototype VPS on existing hardware
**** OpenStack?
* CA Root Key Generation
Nice to have an appliance that manages keys.
Could just buy something from nitrokey https://www.nitrokey.com/
** Need to be clear on security properties.
Definitely protect against remote access to private keys. How strong
does the protection against *local* access need to be?
** Simple hardware.
** USB Serial interface only but no credentials across USB I/F.
But this potentially exposes the hardware to remote access via the USB
I/F when connected.
** Use Sneakernet
Using "disk drive" IO introduces air gap - remote access *impossible*.
Increases attack surface via filesystem manipulation. But use signed
requests, so attacks would have to be insider requests.
** Beagleboard
Found in SCZ. Thought it was in SJ.
** LCD Touchscreen
Unlocks encrypted filesystem. Maybe not needed. See below.
** Morse code PIN
Only need ONE button, and a pass/fail LED. Hardware will never go EOL
(Thanks Elena!). Susceptible to remote audio recording of PIN button
noise, which could be overcome by using 2FA. Again - what am I
protecting against?
** Telephone Keypad or some such
May be more straightforward.
** Encrypted Filesystem
For sensitive material only.
* Virtual Orchestra
** sfz file tests
*** need tooling to edit sample files
** increasingly skeptical whether quality results are possible
** maybe should treat as platform for concatinative synthesis
** maybe should just accept the limitations and work with it
One should not be disappointed that a guitar can't sound like a flute.
* gat
** spectrogram done - matches 'octave' output
* RIOT drivers
Implemented - needs testing.
** WS2801
** Velleman KA03
** Velleman KA05
* mcd05 32 button/led box
** Recovered schematics.
** Planning software.
** Received STM32F767 Nucleo144 with Ethernet.
*** Test program running.
*** Need to consider CoAP multicast discovery.
*** Consider simpler architecture with STM32F767 as a 'hub'.
*** Consider CAN interface to hub.
* AMD 2900 bitslice computing
** Probably my oldest uncompleted project
** Exploring possibilities for something constructive
Create verilog models for 2903/2910 and verify against hardware?
* Hitachi HD68B09E CPU
** RAM/UART/IO
** Started schematic
*** Standard peripheral set for 8 bit CPU bringups
Board schematic planned - need Kicad symbols
** Arduino Mega 2560 DMA loader
...Along with standard 8 bit loader
** Generate quadrature clock directly
** Full Bus SW Emulation infeasible
6809 1000ns maximum cycle time too short
* Rockwell R65F11
** Still evaluating.
** Dev board
Reverse engineered some of a mostly fully built development board with
one part missing. As near as I can tell, that one part is some sort of
programmable address decoder with a pinout that does not correspond to
any part I can find. Kind of like a GAL but with inputs on top and
outputs on bottom (as opposed to left and right in a standard GAL). I
have no idea what the provenance of this board is and if it ever
worked.
* PLD programming
Looks like Atmel 16V8 is the last 5V PLD part left standing. Maybe not
surprising that there still doesn't appear to be a fully open source
tool chain for programming. How hard could it be? (!) Could next-pnr
generic help? Might be easier to use espresso for logic array and program
output logic bits directly for simple stuff.
* EPROM Programming
Found some software for Needham programmer. Need to check electrolytic
caps on ISA board.
* POSIT
** Use POSITs for YRX?
No. Existing library is fine.
* MAME
** Subset builds in debug mode
Full debug fails - not enough disk or memory.
** gs6809 serial IO doesn't work right with PTY and other streams
** ampro (Z80/Z80SIO) *does* work with PTY
** Evaluating what is needed for other emulators.
* More project ideas
** Zuse Z3 simulation in Verilog
   Good excuse for floating point ALU design. Try posit format?
** GMPForth ports to simulators
*** SIMH for some targets (vax)
*** MAME looks interesting for microprocessor system emulations
    How to support ersatz systems?
*** Ports to classic figFORTH targets
** GMPASM assembler
   May be useful for handbuilt and rare systems (DMX1000?).
** Extracting ISO Superboard Forth ROMS for MAME emulation
** 'bwocl' OpenCL tooling
*** Offline compilation
*** Standard Kernel Running
** hardware support for classic 5V CPUs
*** RTX2000, CDP1802 still available!
*** 6502, 68000, 320C30, others on hand
*** CPUs with totally async bus may be supportable without RAM
*** Could use small footprint monitor in asm (gmpmon?)
** Existing 'retro' hardware still working?
*** OSI Superboard
Unknown. Composite to VGA adapter didn't seem to work. Needs analysis.
Found OSI model 610 board underneath!
*** Super Jolt
No output. Needs analysis.
*** Ampro Little Board
Not booting. Needs analysis.
*** Rockwell R65F11 Demo board
UART sending "NO ROM" at 2400 7N1 as expected with 2MHz xtal.
MAME emulator possibilities?
*** NMIX-0016
Works. Found original prom in a parts stash(!).
* David Davies
** Broadcom BCG? Employee indicted for running a brothel.
** New case C1923172, consolidated with *15* Parties.
** Next hearing 2/26/2024
